### ISSUE TITLE
Getting it to work for me... found a few bugs.

### ISSUE THREAD

**Issue by csjewell** [briandfoy/mycpan-app-dpan#2]
Been working with perl -d, reading the logs, etc. getting it to work so I can put a dpan on a subdomain of my .dev web site, and I've ALMOST gotten it working (it actually generates the modules/02packages file and CHECKSUMS, just got to see if it'll do the mailrc and whois files (the log message is there, but the files don't seem to be)

At any rate, thankfully I've been installing these packages into a local-lib, and here's the patch with what I found so far:

```
diff -u -r p5-dpan.orig/lib/perl5/MyCPAN/App/DPAN/Reporter/Minimal.pm p5-dpan/lib/perl5/MyCPAN/App/DPAN/Reporter/Minimal.pm
--- p5-dpan.orig/lib/perl5/MyCPAN/App/DPAN/Reporter/Minimal.pm	2018-05-16 17:09:57.000000000 +0000
+++ p5-dpan/lib/perl5/MyCPAN/App/DPAN/Reporter/Minimal.pm	2021-06-30 03:06:53.248081170 +0000
@@ -402,7 +402,7 @@
 
 	no warnings 'uninitialized';
 	my @files =
-		map  { catfile( $report_dir, $_->[-1] ) }
+		map  { catfile( $report_dir, substr($_->[-1], 0, 1), substr($_->[-1], 0, 2), $_->[-1] ) }
 		grep { ! $Seen{$_->[0]}++ }
 		map  { [ /^(.*)-(.*)\.txt\z/, $_ ] }
 		reverse
diff -u -r p5-dpan.orig/lib/perl5/MyCPAN/App/DPAN.pm p5-dpan/lib/perl5/MyCPAN/App/DPAN.pm
--- p5-dpan.orig/lib/perl5/MyCPAN/App/DPAN.pm	2018-05-16 17:09:57.000000000 +0000
+++ p5-dpan/lib/perl5/MyCPAN/App/DPAN.pm	2021-06-29 13:08:03.872382519 +0000
@@ -272,9 +272,10 @@
 sub components
 	{
 	(
+	[ qw( reporter   MyCPAN::App::DPAN::Reporter::Minimal  get_reporter   ) ],
 	[ qw( queue      MyCPAN::Indexer::Queue                get_queue      ) ],
 	[ qw( dispatcher MyCPAN::Indexer::Dispatcher::Serial   get_dispatcher ) ],
-	[ qw( reporter   MyCPAN::App::DPAN::Reporter::Minimal  get_reporter   ) ],
+        [ qw( indexer    MyCPAN::App::DPAN::Indexer            get_indexer    ) ],
 	[ qw( worker     MyCPAN::Indexer::Worker               get_task       ) ],
 	[ qw( collator   MyCPAN::App::DPAN::Reporter::Minimal  get_collator   ) ],
 # this has to be last because it kicks off everything
diff -u -r p5-dpan.orig/lib/perl5/MyCPAN/Indexer/Interface/Text.pm p5-dpan/lib/perl5/MyCPAN/Indexer/Interface/Text.pm
--- p5-dpan.orig/lib/perl5/MyCPAN/Indexer/Interface/Text.pm	2018-05-16 17:44:13.000000000 +0000
+++ p5-dpan/lib/perl5/MyCPAN/Indexer/Interface/Text.pm	2021-06-30 03:08:44.813377176 +0000
@@ -106,7 +106,8 @@
 		}
 	print "\n";
 
-	my $collator = $self->get_coordinator->get_note( 'collator' );
+	my $collator_type = $self->get_coordinator->get_component( 'indexer' )->collator_type;
+	my $collator = $self->get_coordinator->get_note( $collator_type );
 	$collator->() if ref $collator eq ref sub {};
 	}
 
```

The second patch segment makes sure all the package categories are loaded -- and I seem to recall that the dispatcher package wanted the reporter package loaded already, so that's why the reordering. Then the third patch segment makes sure that the indexer actually finds the collator subref. After that, the first patch segment corrects where the code looks for the reports files (in that case, the log file actually SAID it was checking the wrong location... so easy to find.)

If you'd like, when I'm done, I'll send PRs to you, although you code in a style that makes my lazy eye go even wonkier, sir!

**Comment by csjewell** [comment]
And I was just able to set configuration for the last bit. So things are working for me with the patch.

**Comment by briandfoy** [comment]
Yeah, send PRs.

But also not that in some cases, the system is set up for you to create new modules (or subclasses) to specialize it. These changes look fine for the example modules though.

Which style things bother you?

**Comment by briandfoy** [comment]
Also, I don't think I ever did anything with the mailrc or whois files.

**Comment by csjewell** [comment]
Will get the PR's set up tomorrow or the next day, then!

The two things that most surprised me were (A) 8-space indents, instead of 4, and (B) having the brackets that create a block being indented to the same level as their contents (and the left-bracket being on a new line), as opposed to the brackets being the same level as the containing scope and the contents being indented.  But I'm also of the opinion of "it's your module, I can live with your formatting" so the PR's will follow where you led.

**Comment by briandfoy** [comment]
It's not an 8-space ident—just a one tab indent. Most editors can deal with that to make it any size that you like.

It's not so bad to write it in any way that you are used to and perltidy it later, though.

**Comment by csjewell** [comment]
PR's created, sir! Sorry for not getting them done sooner - had to go into the hospital for a few days.

**Comment by briandfoy** [comment]
I'm closing this is favor of the pull requests you sent.
